USE [TEL-ICP];
GO

SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @Category NVARCHAR(50) = N'Country of Origin';
DECLARE @Actor NVARCHAR(100) = N'Seed.CountryOfOrigin';
DECLARE @Now DATETIME2(7) = GETDATE();

DECLARE @Source TABLE
(
    Key1 NVARCHAR(100) NOT NULL PRIMARY KEY,
    Value1 NVARCHAR(1000) NOT NULL
);

INSERT INTO @Source (Key1, Value1)
VALUES
    (N'AD', N'Andorra'),
    (N'AE', N'United Arab Emirates'),
    (N'AF', N'Afghanistan'),
    (N'AG', N'Antigua and Barbuda'),
    (N'AI', N'Anguilla'),
    (N'AL', N'Albania'),
    (N'AM', N'Armenia'),
    (N'AN', N'Netherlands Antilles'),
    (N'AO', N'Angola'),
    (N'AQ', N'Antarctica'),
    (N'AR', N'Argentina'),
    (N'AS', N'American Samoa'),
    (N'AT', N'Austria'),
    (N'AU', N'Australia'),
    (N'AW', N'Aruba'),
    (N'AX', N'Åland Islands'),
    (N'AZ', N'Azerbaijan'),
    (N'BA', N'Bosnia and Herzegovina'),
    (N'BB', N'Barbados'),
    (N'BD', N'Bangladesh'),
    (N'BE', N'Belgium'),
    (N'BF', N'Burkina Faso'),
    (N'BG', N'Bulgaria'),
    (N'BH', N'Bahrain'),
    (N'BI', N'Burundi'),
    (N'BJ', N'Benin'),
    (N'BL', N'Saint Barthélemy'),
    (N'BM', N'Bermuda'),
    (N'BN', N'Brunei Darussalam'),
    (N'BO', N'Bolivia, Plurinational State of'),
    (N'BQ', N'Bonaire, Saint Eustatius and Saba'),
    (N'BR', N'Brazil'),
    (N'BS', N'Bahamas'),
    (N'BT', N'Bhutan'),
    (N'BV', N'Bouvet Island'),
    (N'BW', N'Botswana'),
    (N'BY', N'Belarus'),
    (N'BZ', N'Belize'),
    (N'CA', N'Canada'),
    (N'CC', N'Cocos (Keeling) Islands'),
    (N'CD', N'Congo, the Democratic Republic of the'),
    (N'CF', N'Central African Republic'),
    (N'CG', N'Congo'),
    (N'CH', N'Switzerland'),
    (N'CI', N'Côte d''Ivoire'),
    (N'CK', N'Cook Islands'),
    (N'CL', N'Chile'),
    (N'CM', N'Cameroon'),
    (N'CN', N'China'),
    (N'CO', N'Colombia'),
    (N'CR', N'Costa Rica'),
    (N'CU', N'Cuba'),
    (N'CV', N'Cape Verde'),
    (N'CW', N'Curaçao'),
    (N'CX', N'Christmas Island'),
    (N'CY', N'Cyprus'),
    (N'CZ', N'Czechia'),
    (N'DE', N'Germany'),
    (N'DJ', N'Djibouti'),
    (N'DK', N'Denmark'),
    (N'DM', N'Dominica'),
    (N'DO', N'Dominican Republic'),
    (N'DZ', N'Algeria'),
    (N'EC', N'Ecuador'),
    (N'EE', N'Estonia'),
    (N'EG', N'Egypt'),
    (N'EH', N'Western Sahara'),
    (N'ER', N'Eritrea'),
    (N'ES', N'Spain'),
    (N'ET', N'Ethiopia'),
    (N'FI', N'Finland'),
    (N'FJ', N'Fiji'),
    (N'FK', N'Falkland Islands (Malvinas)'),
    (N'FM', N'Micronesia, Federated States of'),
    (N'FO', N'Faroe Islands'),
    (N'FR', N'France'),
    (N'GA', N'Gabon'),
    (N'GB', N'United Kingdom'),
    (N'GD', N'Grenada'),
    (N'GE', N'Georgia'),
    (N'GF', N'French Guiana'),
    (N'GG', N'Guernsey'),
    (N'GH', N'Ghana'),
    (N'GI', N'Gibraltar'),
    (N'GL', N'Greenland'),
    (N'GM', N'Gambia'),
    (N'GN', N'Guinea'),
    (N'GP', N'Guadeloupe'),
    (N'GQ', N'Equatorial Guinea'),
    (N'GR', N'Greece'),
    (N'GS', N'South Georgia and the South Sandwich Islands'),
    (N'GT', N'Guatemala'),
    (N'GU', N'Guam'),
    (N'GW', N'Guinea-Bissau'),
    (N'GY', N'Guyana'),
    (N'HK', N'Hong Kong'),
    (N'HM', N'Heard Island and McDonald Islands'),
    (N'HN', N'Honduras'),
    (N'HR', N'Croatia'),
    (N'HT', N'Haiti'),
    (N'HU', N'Hungary'),
    (N'ID', N'Indonesia'),
    (N'IE', N'Ireland'),
    (N'IL', N'Israel'),
    (N'IM', N'Isle of Man'),
    (N'IN', N'India'),
    (N'IO', N'British Indian Ocean Territory'),
    (N'IQ', N'Iraq'),
    (N'IR', N'Iran, Islamic Republic of'),
    (N'IS', N'Iceland'),
    (N'IT', N'Italy'),
    (N'JE', N'Jersey'),
    (N'JM', N'Jamaica'),
    (N'JO', N'Jordan'),
    (N'JP', N'Japan'),
    (N'KE', N'Kenya'),
    (N'KG', N'Kyrgyzstan'),
    (N'KH', N'Cambodia'),
    (N'KI', N'Kiribati'),
    (N'KM', N'Comoros'),
    (N'KN', N'Saint Kitts and Nevis'),
    (N'KP', N'Korea, Democratic People''s Republic of'),
    (N'KR', N'Korea, Republic of'),
    (N'KW', N'Kuwait'),
    (N'KY', N'Cayman Islands'),
    (N'KZ', N'Kazakhstan'),
    (N'LA', N'Lao People''s Democratic Republic'),
    (N'LB', N'Lebanon'),
    (N'LC', N'Saint Lucia'),
    (N'LI', N'Liechtenstein'),
    (N'LK', N'Sri Lanka'),
    (N'LR', N'Liberia'),
    (N'LS', N'Lesotho'),
    (N'LT', N'Lithuania'),
    (N'LU', N'Luxembourg'),
    (N'LV', N'Latvia'),
    (N'LY', N'Libya'),
    (N'MA', N'Morocco'),
    (N'MC', N'Monaco'),
    (N'MD', N'Moldova, Republic of'),
    (N'ME', N'Montenegro'),
    (N'MF', N'Saint Martin (French part)'),
    (N'MG', N'Madagascar'),
    (N'MH', N'Marshall Islands'),
    (N'MK', N'North Macedonia'),
    (N'ML', N'Mali'),
    (N'MM', N'Myanmar'),
    (N'MN', N'Mongolia'),
    (N'MO', N'Macau'),
    (N'MP', N'Northern Mariana Islands'),
    (N'MQ', N'Martinique'),
    (N'MR', N'Mauritania'),
    (N'MS', N'Montserrat'),
    (N'MT', N'Malta'),
    (N'MU', N'Mauritius'),
    (N'MV', N'Maldives'),
    (N'MW', N'Malawi'),
    (N'MX', N'Mexico'),
    (N'MY', N'Malaysia'),
    (N'MZ', N'Mozambique'),
    (N'NA', N'Namibia'),
    (N'NC', N'New Caledonia'),
    (N'NE', N'Niger'),
    (N'NF', N'Norfolk Island'),
    (N'NG', N'Nigeria'),
    (N'NI', N'Nicaragua'),
    (N'NL', N'Netherlands'),
    (N'NO', N'Norway'),
    (N'NP', N'Nepal'),
    (N'NR', N'Nauru'),
    (N'NU', N'Niue'),
    (N'NZ', N'New Zealand'),
    (N'OM', N'Oman'),
    (N'PA', N'Panama'),
    (N'PE', N'Peru'),
    (N'PF', N'French Polynesia'),
    (N'PG', N'Papua New Guinea'),
    (N'PH', N'Philippines'),
    (N'PK', N'Pakistan'),
    (N'PL', N'Poland'),
    (N'PM', N'Saint Pierre and Miquelon'),
    (N'PN', N'Pitcairn'),
    (N'PR', N'Puerto Rico'),
    (N'PS', N'Palestinian Territory, Occupied'),
    (N'PT', N'Portugal'),
    (N'PW', N'Palau'),
    (N'PY', N'Paraguay'),
    (N'QA', N'Qatar'),
    (N'RE', N'Réunion'),
    (N'RO', N'Romania'),
    (N'RS', N'Serbia'),
    (N'RU', N'Russian Federation'),
    (N'RW', N'Rwanda'),
    (N'SA', N'Saudi Arabia'),
    (N'SB', N'Solomon Islands'),
    (N'SC', N'Seychelles'),
    (N'SD', N'Sudan'),
    (N'SE', N'Sweden'),
    (N'SG', N'Singapore'),
    (N'SH', N'Saint Helena, Ascension and Tristan da Cunha'),
    (N'SI', N'Slovenia'),
    (N'SJ', N'Svalbard and Jan Mayen'),
    (N'SK', N'Slovakia'),
    (N'SL', N'Sierra Leone'),
    (N'SM', N'San Marino'),
    (N'SN', N'Senegal'),
    (N'SO', N'Somalia'),
    (N'SR', N'Suriname'),
    (N'SS', N'South Sudan'),
    (N'ST', N'Sao Tome and Principe'),
    (N'SV', N'El Salvador'),
    (N'SX', N'Sint Maarten (Dutch part)'),
    (N'SY', N'Syrian Arab Republic'),
    (N'SZ', N'Eswatini'),
    (N'TC', N'Turks and Caicos Islands'),
    (N'TD', N'Chad'),
    (N'TF', N'French Southern Territories'),
    (N'TG', N'Togo'),
    (N'TH', N'Thailand'),
    (N'TJ', N'Tajikistan'),
    (N'TK', N'Tokelau'),
    (N'TL', N'Timor-Leste'),
    (N'TM', N'Turkmenistan'),
    (N'TN', N'Tunisia'),
    (N'TO', N'Tonga'),
    (N'TR', N'Turkey'),
    (N'TT', N'Trinidad and Tobago'),
    (N'TV', N'Tuvalu'),
    (N'TW', N'Taiwan, Province of China'),
    (N'TZ', N'Tanzania, United Republic of'),
    (N'UA', N'Ukraine'),
    (N'UG', N'Uganda'),
    (N'UM', N'United States Minor Outlying Islands'),
    (N'US', N'United States'),
    (N'UY', N'Uruguay'),
    (N'UZ', N'Uzbekistan'),
    (N'VA', N'Holy See (Vatican City State)'),
    (N'VC', N'Saint Vincent and the Grenadines'),
    (N'VE', N'Venezuela, Bolivarian Republic of'),
    (N'VG', N'Virgin Islands, British'),
    (N'VI', N'Virgin Islands, U.S.'),
    (N'VN', N'Viet Nam'),
    (N'VU', N'Vanuatu'),
    (N'WF', N'Wallis and Futuna'),
    (N'WS', N'Samoa'),
    (N'YE', N'Yemen'),
    (N'YT', N'Mayotte'),
    (N'ZA', N'South Africa'),
    (N'ZM', N'Zambia'),
    (N'ZW', N'Zimbabwe'),
    (N'ZZ', N'ZZZ');

UPDATE target
SET target.Value1 = source.Value1,
    target.UpdateTime = @Now,
    target.UpdateUser = @Actor
FROM dbo.SystemConfigs AS target
INNER JOIN @Source AS source ON source.Key1 = target.Key1
WHERE target.Category = @Category
  AND target.FunctionCode IS NULL
  AND target.Key2 = N''
  AND target.IsDeleted = 0
  AND ISNULL(target.Value1, N'') <> source.Value1;

INSERT INTO dbo.SystemConfigs
(
    Category,
    FunctionCode,
    Key1,
    Key2,
    Value1,
    Value2,
    Value3,
    Value4,
    Value5,
    Value6,
    IsDeleted,
    CreateTime,
    CreateUser,
    UpdateTime,
    UpdateUser
)
SELECT
    @Category,
    NULL,
    source.Key1,
    N'',
    source.Value1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    @Now,
    @Actor,
    NULL,
    NULL
FROM @Source AS source
WHERE NOT EXISTS
(
    SELECT 1
    FROM dbo.SystemConfigs AS target WITH (UPDLOCK, HOLDLOCK)
    WHERE target.Category = @Category
      AND target.FunctionCode IS NULL
      AND target.Key1 = source.Key1
      AND target.Key2 = N''
      AND target.IsDeleted = 0
);

COMMIT TRANSACTION;

SELECT Key1, Value1
FROM dbo.SystemConfigs
WHERE Category = N'Country of Origin'
  AND FunctionCode IS NULL
  AND Key2 = N''
  AND IsDeleted = 0
ORDER BY Key1;
GO

